services:
  web:
    image: web
    restart: always
    build:
      context: ./src/Web
      dockerfile: Dockerfile
      image: ghcr.io/sdbrannum/golfkc-web:latest
    expose:
      - 8080
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    links:
      - web
volumes:
  caddy_data:
  caddy_config: