services:
  web:
    image: web
    restart: always
    build:
      context: ./src/Web
      dockerfile: Dockerfile
    expose:
      - 8080
  # proxy:
  #   image: nginx:latest
  #   restart: always
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   # volumes:
  #   #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - web
  #   ports:
  #     - "80:80"
  #     # - "443:443"
  #   links:
  #     - web
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    links:
      - web
volumes:
  caddy_data:
  caddy_config: